### ISSUE TITLE
Surge 3 默认规则集导致网易云音乐 iPad 版无法加载

### ISSUE THREAD

**Issue by AlanDecode** [rixCloud-Inc/rixCloud_Surge-Data#19]
问题出在这一行：
https://github.com/rixCloud-Inc/rixCloud_Surge-Data/blob/37b7500678e23e4a4def43f01d90489fb5e11697/surge3_rules#L5

**Comment by ZeroClover** [comment]
我们不处理 issue，请自行 PR 或使用 Cloud Profile
